In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("cibil_nn.csv")

In [3]:
df.head()

,Unnamed: 0,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,45,46,12,7,5,7,4,0.583,0.333,0.417,...,1.0,0.615,1.000,7.729,0,0,CC,others,651,P4
1,183,184,9,5,4,0,0,0.000,0.000,0.444,...,1.0,0.286,0.286,23.113,0,0,PL,others,672,P2
2,351,352,4,0,4,1,0,0.250,0.000,1.000,...,0.0,0.000,0.000,5.582,0,1,HL,CC,689,P2
3,403,404,129,122,7,0,7,0.000,0.054,0.054,...,1.0,0.500,0.429,2.218,1,0,ConsumerLoan,AL,649,P4
4,493,494,4,1,3,1,0,0.250,0.000,0.750,...,1.0,0.333,1.000,6.192,0,0,PL,PL,662,P3

In [4]:
df.columns

Index(['Unnamed: 0', 'PROSPECTID', 'Total_TL', 'Tot_Closed_TL',
       'Tot_Active_TL', 'Total_TL_opened_L6M', 'Tot_TL_closed_L6M',
       'pct_tl_open_L6M', 'pct_tl_closed_L6M', 'pct_active_tl',
       'pct_closed_tl', 'Total_TL_opened_L12M', 'Tot_TL_closed_L12M',
       'pct_tl_open_L12M', 'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL',
       'CC_TL', 'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL',
       'time_since_recent_payment', 'time_since_first_deliquency',
       'time_since_recent_deliquency', 'num_times_delinquent',
       'max_delinquency_level', 'max_recent_level_of_deliq', 'num_deliq_6mts',
       'num_deliq_12mts', 'num_deliq_6_12mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std',
       'num_std_6mts', 'num_std_12mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_dbt_12mts', 'num_lss',
       'num_lss_6mts', 'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq',
       'CC_enq', 'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L12m', 'enq_L6m',
       'enq_L3m', 'MARITALSTATUS', 'EDUCATION', 'AGE', 'GENDER',
       'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_utilization',
       'CC_Flag', 'PL_utilization', 'PL_Flag', 'pct_PL_enq_L6m_of_L12m',
       'pct_CC_enq_L6m_of_L12m', 'pct_PL_enq_L6m_of_ever',
       'pct_CC_enq_L6m_of_ever', 'max_unsec_exposure_inPct', 'HL_Flag',
       'GL_Flag', 'last_prod_enq2', 'first_prod_enq2', 'Credit_Score',
       'Approved_Flag'],
      dtype='object')

In [5]:
df.shape

(585, 88)

In [6]:
df.describe()

,Unnamed: 0,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,...,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,Credit_Score
count,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,...,585.000000,585.0,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000
mean,25600.707692,25601.707692,14.517949,8.170940,6.347009,1.849573,1.328205,0.146655,0.083145,0.553010,...,0.724156,1.0,0.422656,0.326350,0.250899,0.193287,242.707275,0.379487,0.150427,677.547009
std,14981.649883,14981.649883,12.873998,10.922744,3.722975,2.290825,1.882228,0.163755,0.107114,0.229431,...,0.250704,0.0,0.419381,0.410247,0.306609,0.284189,3889.132647,0.485675,0.357796,28.276308
min,45.000000,46.000000,2.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.047000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.444000,0.000000,0.000000,561.000000
25%,13186.000000,13187.000000,6.000000,2.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.379000,...,0.623000,1.0,0.000000,0.000000,0.000000,0.000000,7.101000,0.000000,0.000000,662.000000
50%,24711.000000,24712.000000,11.000000,5.000000,6.000000,1.000000,1.000000,0.105000,0.050000,0.538000,...,0.783000,1.0,0.333000,0.000000,0.133000,0.000000,11.362000,0.000000,0.000000,676.000000
75%,38895.000000,38896.000000,18.000000,10.000000,8.000000,3.000000,2.000000,0.222000,0.143000,0.692000,...,0.918000,1.0,0.909000,0.667000,0.400000,0.333000,18.981000,1.000000,0.000000,694.000000
max,51282.000000,51283.000000,129.000000,122.000000,24.000000,16.000000,11.000000,0.889000,0.600000,1.000000,...,1.044000,1.0,1.000000,1.000000,1.000000,1.000000,83672.100000,1.000000,1.000000,795.000000

In [7]:
df[['AGE','Credit_Score','Approved_Flag']].head()

   AGE  Credit_Score Approved_Flag
0   25           651            P4
1   32           672            P2
2   34           689            P2
3   28           649            P4
4   25           662            P3

In [8]:
X = df.drop(columns=['Credit_Score'])
y = df['Credit_Score']

In [9]:
obj_cols = X.select_dtypes(include='object').columns

X = pd.get_dummies(X, columns=obj_cols, drop_first=True)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = model.predict(X_test)

In [14]:
r2 = (y_test, y_pred)

In [16]:
from sklearn.metrics import r2_score

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.9485966348010563

In [17]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

MAE: 5.12897524674055

In [18]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)

print("MSE:", mse)

MSE: 35.60736529259563

In [19]:
rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 5.967190737071812

In [ ]:
X = df.drop(columns=['Approved_Flag'])
y = df['Approved_Flag']

In [ ]:
obj_cols = X.select_dtypes(include='object').columns

X = pd.get_dummies(X, columns=obj_cols, drop_first=True)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, Y_train)

c:\Users\Sumit's\OneDrive\Desktop\M.L_01\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, Y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.6239316239316239

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, Y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[13  7  0  0]
 [ 4 42  1  6]
 [ 1 16  1  3]
 [ 0  3  3 17]]

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

          P1       0.72      0.65      0.68        20
          P2       0.62      0.79      0.69        53
          P3       0.20      0.05      0.08        21
          P4       0.65      0.74      0.69        23

    accuracy                           0.62       117
   macro avg       0.55      0.56      0.54       117
weighted avg       0.57      0.62      0.58       117

In [ ]:
import math

def sigmoid(z):
    return 1 / (1 + math.exp(-z))

# Test
print(sigmoid(2))

0.8807970779778823

In [ ]:
def sigmoid(z):
    return 1 / (1 + math.exp(-z))

values = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]

for i in values:
    print(f"Sigmoid({i}) = {sigmoid(i):.4f}")

Sigmoid(-5) = 0.0067
Sigmoid(-4) = 0.0180
Sigmoid(-3) = 0.0474
Sigmoid(-2) = 0.1192
Sigmoid(-1) = 0.2689
Sigmoid(0) = 0.5000
Sigmoid(1) = 0.7311
Sigmoid(2) = 0.8808
Sigmoid(3) = 0.9526
Sigmoid(4) = 0.9820